changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: "🚨 Breaking Changes"
      labels:
        - breaking-change
    - title: "✨ New Features"
      labels:
        - feat
    - title: "🐛 Bug Fixes"
      labels:
        - fix
    - title: "⚡ Performance"
      labels:
        - perf
    - title: "♻️ Refactors"
      labels:
        - refactor
    - title: "🔧 CI/CD"
      labels:
        - ci
    - title: "📦 Build"
      labels:
        - build
    - title: "🧹 Chores"
      labels:
        - chore
    - title: "Other Changes"
      labels:
        - "*"